locallibrary/catalog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    url(r'^authors/$', views.AuthorsListView.as_view(), name='authors'),
    url(r'^author/(?P<pk>\d+)$', views.AuthorDetailView.as_view(), name='author-detail'),
    url(r'^mybooks/$', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    url(r'^staffbooks/$', views.AllBooksInstancesListView.as_view(), name='staff-borrowed'),
    url(r'^book/(?P<pk>[-\w]+)/renew/$', views.renew_book_librarian, name='renew-book-librarian'),
    url(r'^author/create/$', views.AuthorCreate.as_view(), name='author_create'),
    url(r'^author/(?P<pk>\d+)/update/$', views.AuthorUpdate.as_view(), name='author_update'),
    url(r'^author/(?P<pk>\d+)/delete/$', views.AuthorDelete.as_view(), name='author_delete'),
    url(r'^book/create/$', views.BookCreate.as_view(), name='book_create'),
    url(r'^book/(?P<pk>[-\w]+)/update/$', views.BookUpdate.as_view(), name='book_update'),
    url(r'^book/(?P<pk>[-\w]+)/delete/$', views.BookDelete.as_view(), name='book_delete'),
]

locallibrary/locallibrary/urls.py
from django.contrib import admin

from django.urls import path
from django.urls import include

from django.views.generic import RedirectView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

locallibrary/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date
import uuid

class Genre(models.Model):
    """
    Model representing a book genre (e.g. Science Fiction, Non Fiction).
    """
    name = models.CharField(max_length=200, help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)')

    def __str__(self):
        '''
        String for representing the Model object (in Admin site etc.)
        '''

        return self.name


class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the book')
    isbn = models.TextField('ISBN', max_length=13, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')

    def __str__(self):
        '''
        String for represting the Model object.
        '''
        return self.title
    
    def get_absolute_url(self):
        return reverse("book-detail", args=[str(self.id)])
    
    def display_genre(self):
        """
        Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([genre.name for genre in self.genre.all()[:3]])
    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    '''
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    '''
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    book = models.ForeignKey('Book', on_delete=models.SET_NULL, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Aviable'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='m', help_text='Book availability')

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mar_returned', 'Set book as returned'), )
    
    def __str__(self):
        """
        String for representing the Model object
        """
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """
    Model representing an author
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    def get_absolute_url(self):
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return f'{self.last_name}, {self.first_name}'
    
    class Meta:
        ordering = ['last_name']

locallibrary/catalog/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
import datetime

class RenewBookForm(forms.Form):
    renewal_date = forms.DateField(help_text='Enter a date between now and 4 weeks (default 3).')

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_data']

        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        return data

locallibrary/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from .models import Book, Author, BookInstance, Genre
from .forms import RenewBookForm

import datetime

# Create your views here.
def index(request):
    """
    Function to view homepage.
    """
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='a').count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()

    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1

    return render(
        request,
        'index.html',
        context={'num_books':num_books, 'num_instances':num_instances, 'num_instances_available':num_instances_available, 'num_authors':num_authors, 'num_genres':num_genres, 'num_visits':num_visits}
    )


class BookListView(generic.ListView):
    model = Book
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.all()
    

class BookDetailView(generic.DetailView):
    model = Book


class AuthorsListView(generic.ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(generic.DetailView):
    model = Author


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """
    Generic class-based view listing books on loan to current User
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

class AllBooksInstancesListView(LoanedBooksByUserListView, PermissionRequiredMixin):
    permission_required = 'catalog.can_mark_returned'
    def get_queryset(self):
        return BookInstance.objects.all().order_by('due_back')

@permission_required('catalog.can_mark_returned')
def renew_book_librarian(request, pk):
    """
    View function for renewing a specific BookInstane by librarian
    """
    book_inst = get_object_or_404(BookInstance, pk=pk)

    if request.method == "POST":
        form = RenewBookForm(request.POST)

        if form.is_valid():
            book_inst.due_back = form.cleaned_data['renewal_date']
            book_inst.save()
        else:
            return HttpResponseRedirect(reverse('/'))
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)

        form = RenewBookForm(initial={'renewal_date': proposed_renewal_date,})
    
    return render(request, 'catalog/book_renew_librarian.html', {'form': form, 'bookinst':book_inst})


class AuthorCreate(CreateView):
    model = Author
    fields = '__all__'


class AuthorUpdate(UpdateView):
    model = Author
    fields = '__all__'

class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('authors')


class BookCreate(CreateView):
    model = Book
    fields = '__all__'


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')

locallibrary/catalog/templates/catalog/author_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Delete Author</h1>
<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_detail.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Last Name: {{ author.last_name }}</h1>

    <p><strong>First Name:</strong> {{ author.first_name }}</p>
    <p><strong>Date of birth:</strong> {{ author.date_of_birth }}</p>
    <p><strong>Date of death:</strong> {{ author.date_of_death }}</p>
{% endblock %}

locallibrary/catalog/templates/catalog/author_form.html
{% extends 'base_generic.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Authors List</h1>
    {% if author_list %}
    <ul>
        {% for author in author_list %}
        <li>
            <a href="{{ author.get_absolute_url }}">{{ author.last_name }} {{ author.first_name }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no authors in the library</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_confirm_delete.html
{% extends 'base_generic.html' %}
{% block content %}
<h1>Delete Book</h1>
<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_detail.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong><a href=""> {{ book.author }}</a></p>
    <p><strong>Summary:</strong><a href=""> {{ book.summary }}</a></p>
    <p><strong>ISBN:</strong><a href=""> {{ book.isbn }}</a></p>
    <p><strong>Genres:</strong>
        {% for genre in book.genre.all %}
            {{ genre}} {% if not forloop.last %} {% endif %}
        {% endfor %}
    </p>

    <div style="margin-top: 20px;">
        <h4>Copies</h4>
        {% for copy in book.bookinstance_set.all %}
        <hr>
        <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
        
        {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong>{{ copy.due_back }}</p>
        {% endif %}
        <p><strong>Imprint:</strong> {{copy.imprint}}</p>
        <p class="text-muted"><strong>ID:</strong> {{copy.id}}</p>
        {% endfor %}
    </div>
{% endblock %}

locallibrary/catalog/templates/catalog/book_form.html
{% extends 'base_generic.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table}}
    </table>
    <input type="submit" value="Submit">
</form>
{% endblock %}

locallibrary/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
        <li>
            <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library</p>
    {% endif %}
{% endblock %}

locallibrary/catalog/templates/catalog/book_renew_librarian.html
{% extends 'base_generic.html' %}
{% block content %}
    <h1>Renew: {{ bookinst.book.title }}</h1>
    <p>Borrower: {{ bookinst.borrower }}</p>
    <p {% if bookinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{ bookinst.due_back }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

locallibrary/catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>
      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }})        
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}       
{% endblock %}